# Generated by Django 5.0.7 on 2024-08-13 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_account_options'),
        ('airlines', '0003_airline_created_at_airline_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('paid_miles', models.PositiveIntegerField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=250, null=True)),
                ('owner', models.CharField(max_length=200)),
                ('miles_price', models.FloatField(blank=True, null=True)),
                ('current_miles_balance', models.IntegerField()),
                ('due_date', models.DateField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.account')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airline', to='airlines.airline')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
