# Generated by Django 5.0.7 on 2024-08-21 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('clients', '0002_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledLap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_date', models.DateField()),
                ('account_login', models.CharField(max_length=200)),
                ('individual_cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tickets_number', models.IntegerField()),
                ('individual_profit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('posted_by', models.CharField(max_length=50)),
                ('total_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('refunded_on_card', models.BooleanField(default=False)),
                ('cancellation_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_verified', models.BooleanField(default=False)),
                ('ticket_locator', models.CharField(max_length=20)),
                ('passenger_last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('cancellation_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('A Cancelar', 'A Cancelar'), ('Cancelada', 'Cancelada'), ('Marcio', 'Marcio'), ('Daniel', 'Daniel'), ('Jessica', 'Jessica'), ('Revisando', 'Revisando')], max_length=100)),
                ('annotations', models.TextField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canceled_laps', to='clients.client')),
                ('credit_card', models.ManyToManyField(related_name='canceled_laps', to='cards.card')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
