# Generated by Django 5.0.7 on 2024-08-07 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airline',
            options={'ordering': ['name']},
        ),
    ]
