# Generated by Django 5.0.7 on 2024-08-07 01:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_alter_airline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
